name: pharmacies_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  bottom_bar_matu: ^1.4.0
  buttons_tabbar: ^1.3.8
  carousel_slider: ^4.2.1
  custom_sliding_segmented_control: ^1.8.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
flutter_intl:
  enabled: true
